### API 1

GET http://localhost:3000/players/

### API 2

GET http://localhost:3000/players/1

### API 3

PUT http://localhost:3000/players/1

{
  "playerName": "Raju"
}

###

GET http://localhost:3000/matches/18/

###

GET http://localhost:3000/players/3/matches


### API 7
http://localhost:3000/players/1/playerScores

